@startuml

Game "1" *-- "*" Player
Game "1" *-- "3" Card
Game "1" *-- "*" Weapon
Player "1" *-- "*" Card
Player "1" *-- "1" Room
Controller "1" *-- "1" Game

class Game {
players
weapons: Map<Weapon, Room>
winningCards
activePlayer
turnOrder
}

class Player {
character
cards
room
messageChannel
}

enum Weapon {
name
}

enum Card {
name
iconUrl
type
}

enum Room {
name
type
}

class Controller {
game
movePlayer()
guess()
...()
}

@enduml
