@startuml

Game "1" *-- "*" Player
Game "1" *-- "3" Card
Player "1" *-- "*" Card
Room "1" *-- "?" Player

class Game {
players
winningCards
activePlayer
rooms
movePlayer()
guess()
...()
}

class Player {
character
cards
messageChannel
}

class Card {
name
iconUrl
}

class Room {
name
player
}

@enduml
